const listProducts = [
  {
    id: 1,
    name: "Tazas",
    disp:"Disponibles:",
    stock: 5,
    cost: "$450",
    descrip: "Para Personalizar",
    vista: require("../imagen/taza.png"),
    productos: "Productos",
  },
  {
    id: 2,
    name: "Remeras",
    disp:"Disponibles:",
    stock: 10,
    cost: "$190",
    descrip: "Para Personalizar",
    vista: require("../imagen/remera.png"),
    productos: "Productos",
  },
  {
    id: 3,
    name: "Termos",
    disp:"Disponibles:",
    stock: 8,
    cost: "$800",
    descrip: "Para Personalizar",
    vista: require("../imagen/termo.png"),
    productos: "Productos",
  },
  {
    id: 4,
    name: "Buzos",
    disp:"Disponibles:",
    stock: 5,
    cost: "$1800",
    descrip: "Para Personalizar",
    vista: require("../imagen/buzo.png"),
    productos: "Productos",
  },
  {
    id: 5,
    name: "LLaveros",
    disp:"Disponibles:",
    stock: 15,
    cost: "$300",
    descrip: "Para Personalizar",
    vista: require("../imagen/llavero.png"),
    productos: "Productos",
  },
];

export default listProducts;
